version: '3.6'

services:
  api:
    build:
      context: ../../src/MicroCommunication.Api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - ApiKey=
  web:
    build:
      context: ../../src/MicroCommunication.Web
      dockerfile: Dockerfile
    ports:
      - '5000:8080'
    environment:
      - API_URL=http://localhost:8080
      - API_KEY=
