version: '3.6'

services:
  api:
    image: robinmanuelthiel/microcommunication-api:latest
    build:
      context: src/MicroCommunication.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  web:
    image: robinmanuelthiel/microcommunication-web:latest
    build:
      context: src/MicroCommunication.Web
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - RandomApiHost=http://api:8080/api/random
