version: '3.6'

services:
  api:
    build:
      context: ../../src/api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - ApiKey=
  web:
    build:
      context: ../../src/web
      dockerfile: Dockerfile
    ports:
      - '5000:8080'
    environment:
      - API_URL=http://localhost:8080
      - API_KEY=
