#######################################################
# API                                                 #
#######################################################

kind: Service
apiVersion: v1
metadata:
  name: api
#  annotations:
#    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
#    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "api-ingress-subnet"
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---

#######################################################
# Web Frontend                                        #
#######################################################

kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
