# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  displayName: 'Build and push API Docker image'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'robinmanuelthiel/contosomaintenance-api'
    command: 'buildAndPush'
    Dockerfile: 'src/MicroCommunication.Api/Dockerfile'
    buildContext: 'src/MicroCommunication.Api'
    tags: |
     1.0.$(Build.BuildId)
     latest

- task: Docker@2
  displayName: 'Build and push Web Docker image'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'robinmanuelthiel/contosomaintenance-web'
    command: 'buildAndPush'
    Dockerfile: 'src/MicroCommunication.Web/Dockerfile'
    buildContext: 'src/MicroCommunication.Web'
    tags: |
     1.0.$(Build.BuildId)
     latest
