name: Build and push Docker Images
on:
  push:
    paths: 
      - src
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v1  
        
      - name: Build API image
        run: docker build src/MicroCommunication.Api --file src/MicroCommunication.Api/Dockerfile --tag robinmanuelthiel/microcommunication-api:$(date +%s) --tag robinmanuelthiel/microcommunication-api:latest    

      - name: Build Web image
        run: docker build src/MicroCommunication.Web --file src/MicroCommunication.Web/Dockerfile --tag robinmanuelthiel/microcommunication-web:$(date +%s) --tag robinmanuelthiel/microcommunication-web:latest    

      - name: Login to Docker Hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push API image
        run: docker push robinmanuelthiel/microcommunication-api

      - name: Push Web image
        run: docker push robinmanuelthiel/microcommunication-web

